{
 "title": "Daemon Stats",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(monerod_connections_incoming)",
     "legendFormat": "Incoming"
    },
    {
     "expr": "avg(monerod_connections_outgoing)",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Block Reward (WOW)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "avg(monerod_block_reward)", "legendFormat": "Block Reward (WOW)" }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "avg(monerod_block_difficulty)" }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(monerod_tx_mempool)", "legendFormat": "Pool Transactions" }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(monerod_tx_chain)" }
   ]
  }
 ]
}