global:
  scrape_interval: 30s
  evaluation_interval: 60s

  external_labels:
    monitor: xolentumd-exporter

scrape_configs:
  - job_name: "xolentumd-exporter"
    static_configs:
      - targets: ["exporter:8080"]

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093
